### ISSUE TITLE
BVC-170: Key Errors still generate Database Objects 

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-portal#144]
Valid for commit: https://github.com/cds-snc/covid-alert-portal/commit/eddd3554537dd74b34dd0e0d0f9876af25d48b89 - Connect to preview 

https://github.com/cds-snc/covid-alert-portal/blob/main/covid_key/views.py#L45

```
if token:
    try:
        r = requests.post(
            settings.API_ENDPOINT, headers={"Authorization": f"Bearer {token}"}
        )
        r.raise_for_status()  # If we don't get a valid response, throw an
        # exception
        # Make sure the code has a length of 10, cheap sanity check
        if len(r.text.strip()) == 10:
            diagnosis_code = r.text
        else:
            # Error is logged only, but flow is uninterrupted  <----------
            logger.error(
                f"The key API returned a key with the wrong format : {r.text}"
            )
    except requests.exceptions.HTTPError as err:
        # Exception is caught and logged, but flow is uninterrupted  <----------
        logging.exception(
            f"Received {r.status_code} with message {err.response.text}"
        )
    except requests.exceptions.RequestException as err:
        # Exception is caught and logged, but flow is uninterrupted  <----------
        logging.exception(f"Something went wrong {err}")
        
# Flow continues here to creating the database entry and returning a form to the user  <----------
covid_key = COVIDKey()

```
# ...
None of the error cases here prevent creation of a COVIDKey database object, nor do they display an error to the HCP user.

At the very least, the database object should not be made. Doing so will contribute to the number of keys that can be made in a day, so a user could easily get locked out in making repeated requests trying to generate a valid code.

Ideally the user should also be made aware of an error, rather than just a 000 000 0000 key being displayed.

**Comment by PierrePaul** [comment]
This issue has been put in the internal trello board : https://trello.com/c/mlZ4q1X1/230-dont-create-a-key-object-unless-the-key-retrieval-worked
This has been fixed in PR 150 : https://github.com/cds-snc/covid-alert-portal/pull/150

We moved the logic of the CovidKey creation object into the try catch.
We also changed the try catch to send a flash message to the user if an error happened when generating the key.
If an error occurred, we no longer show the '000 000 0000' key to the user, only the error, the instructions and the _Next patient_ button.

Thanks for the report!
