### ISSUE TITLE
Alignment of "delete" in manage team page

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#282]
@pcraig3 on the manage team page, please make "delete" a separate column, as in figma

https://staging.covid-hcportal.cdssandbox.xyz/en/profiles/

Thanks!

**Comment by pcraig3** [comment]
Hello!

So our implementation is a clone of the GOV.UK [Summary List](https://design-system.service.gov.uk/components/summary-list/) example, which is a table with 3 columns.

```
| id or name | value | actions (edit, remove) |
```

Basically, the "edit" buttons are grouped in the same column together, and a screen reader will announce that as the "Actions" column.

in this screenshot, you can see they are both in the same cell.

![image](https://user-images.githubusercontent.com/2454380/95620192-c89dce00-0a3d-11eb-9204-a7aefd1dda79.png)

They are side-by-side sometimes if the screen size is large enough and otherwise they collapse one on top of each other. 

![cols](https://user-images.githubusercontent.com/2454380/95620097-aa37d280-0a3d-11eb-9087-6b4ed56e45b5.gif)

I think it makes sense to keep them in the same column, because we don't always have 2 values there (eg, admins can't delete other admins). Btu we could add more space underneath the values if it would differentiate them more cleanly.

**Comment by YedidaZalik** [comment]
@pcraig3  @brianhendrick1 i think visually "delete" should be on the same  line as "edit" as otherwise people may think it is for a different user.
If adding more space would solve that, then great!

**Comment by dsamojlenko** [comment]
Closing as stale/not a priority
