### ISSUE TITLE
Changes to "Your account" Flow

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#339]
@pcraig3 

**Your account screen**

Please change “Your account” to “Manage your account” (both for page heading and header in top nav bar)

Mobile phone number  - please replace "N/A" with “Not using”

Security codes - please replace “None generated” with “None used yet” 

**Security codes screen** (aka Offline 2FA logged in screen)

Please change “Back to your account”  to  “Back to Manage your account” 

Please change the French versions of the 2 screens above as shown in the mock-ups: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=4361%3A0

**Comment by pcraig3** [comment]
Hello! We can make all of these changes, but I wanted to clarify something.

 > Security codes - please replace “None generated” with “None used yet”

The reason I didn't put in "None used yet", is because its meaning is ambiguous. Users can be in one of two states
1. they _never_ created backup codes (you have 0 codes because you've never generated any)
2. they created them, but haven't used any (you have 10 codes left)

"None used yet" could apply to both cases. Eg, you haven't created codes, so none used yet, OR you created 10 but you haven't used any, so none used yet.  This message is what we will show users who haven't generated any codes ever, so "None generated" was the filler text we used to make that distinction clear.

If you want to keep "None used yet", I'm fine to put it in, but I just wanted to highlight that before making the change.

**Comment by YedidaZalik** [comment]
@pcraig3 
Here is the new content in both languages incorporating your comments.

Security codes Never generated Generate codes

Codes de sécurité	  Pas encore générés	Générer des codes


Merci beaucoup @pcraig3 !
