### ISSUE TITLE
Changes to "Onboarding /Account creation" flow

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#343]
@pcraig3 

**Create account screen** aka Account Creation

Please change as follows 
All the hint text is given but there should be one line: “Your password must be at least 12 characters and hard to guess.” 
The other hint text is only meant to show if the user makes that particular error.

Please replace
Confirm your password
Enter the same password as above.
 with “Enter your password again.” and in the French as this mockup "Saisissez de nouveau votre mot de passe."

Please change “Create account” to “Next”

**Enter mobile phone number screen**
Under the heading, please remove “Mobile phone number”

Please change the French version to follow this mock-up https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=4571%3A29106

**Enter your security code screen -** aka Two-Factor (no mobile)
Please change” You kept these codes on paper.” To “You kept these codes somewhere safe”
Please remove “Security code” over box

Please change French version to this mock-up https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=4571%3A28908

**Enter one of your security codes screen** aka Two-Factor mobile + backup codes
Please change to “We’ve texted you a code and you also kept codes somewhere safe.”
Please remove “Security code” over box

Please change French version to this mock-up https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=4740%3A12

**No security code screen** aka Resend Two-Factor (no mobile)
Please change to Ask your administrator for a code. You can email them at  admin@email.com.  
And in French please change to: Demandez à votre administrateur de vous donner un code. Vous pouvez leur envoyer un courriel à admin@email.com.

**Request for security codes email**
Please replace “To generate security codes” with “To give them a code:”
Please replace  “Portal” with “portal”
Please replace “Edit” with “Manage”
On line Go to ‘Security codes’ row. select ‘Get security code’. Please remove “select ‘Get security code”
On next line please remove space between ‘ and Get
In the line “Read. . . “ please remove the “s” at the end of codes.
Please replace “Placeholder for French” with the French.

Please reverse the order for emails to Quebec.

**Comment by pcraig3** [comment]
> All the hint text is given but there should be one line: “Your password must be at least 12 characters and hard to guess.”
The other hint text is only meant to show if the user makes that particular error.

Not sure if we should change the hint text. See [my comment in issue #340](https://github.com/cds-snc/covid-alert-portal/issues/340#issuecomment-752692578).

> Under the heading, please remove “Mobile phone number”
> Please remove “Security code” over box

In both cases, these are the form field labels. If someone using a screen reader enters the input box, the screen reader will read the form label to them. Removing the label is an a11y violation, so we want to keep it in.

We could also change the text of the page title or the form label, but the current ones we have are pretty clear (if redundant).

My suggestion is that we just keep the duplication around. You're right that it's unneeded in most cases, but it's pretty much a rule of form design that you always need labels with forms, and rather than coming up with new text just for the sake of being different, I think it's fine as it is.

___

The rest of the changes won't be a problem.
